primary_hub_ocp_host: https://api.aro-XYZ:6443/
primary_hub_ocp_api_key: 'sha256~XXX' 
primary_hub_ocp_validate_certs: False

secondary_hub_ocp_host: https://api.rosa-XYZ:6443
secondary_hub_ocp_api_key: 'sha256~'
secondary_hub_ocp_validate_certs: False

managed_cluster_name: managed-cluster
managed_cluster_ocp_host: https://api.cluster-XYZ:6443
managed_cluster_ocp_api_key: 'sha256~'
managed_cluster_ocp_validate_certs: False

aws_access_key: 
aws_secret_key: ''