- name: Verify that the cluster API are reachable and the credential are correct
  kubernetes.core.k8s_cluster_info:
    host: "{{host}}"
    api_key: "{{api_key}}"
    validate_certs: "{{validate_certs}}"
  register: api_status

- name: Delete BackupSchedule resource if it exists on the passive ACM HUB
  kubernetes.core.k8s:
    host: "{{host}}"
    api_key: "{{api_key}}"
    validate_certs: "{{validate_certs}}"
    state: absent
    api_version: v1beta1
    kind: BackupSchedule
    name: schedule-acm
    namespace: open-cluster-management-backup    
  retries: 100
  delay: 5
  register: result
  until: result is success  
  

- name: create GCP S3 bucket cloud credential secret
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: Secret
      type: Opaque             
      metadata:
        name: "cloud-credentials"
        namespace: open-cluster-management-backup
      data:
         cloud: "{{ acm_velero_service_account_credential | b64encode }}"
    host: "{{host}}"
    api_key: "{{api_key}}"
    validate_certs: "{{validate_certs}}"
  retries: 100
  delay: 5
  register: result
  until: result is success

- name: Enable the Managed Service Account component
  kubernetes.core.k8s:
    host: "{{host}}"
    api_key: "{{api_key}}"
    validate_certs: "{{validate_certs}}"
    definition:
      apiVersion: multicluster.openshift.io/v1
      kind: MultiClusterEngine
      metadata:
        name: multiclusterengine
      spec:
        overrides:
          components:
          - enabled: true
            name: managedserviceaccount-preview
    apply: yes
  ignore_errors: true


- name: create ACM DataProtectionApplication resource
  kubernetes.core.k8s:
    host: "{{host}}"
    api_key: "{{api_key}}"
    validate_certs: "{{validate_certs}}"
    state: present
    template: templates/06_DataProtectionApplication_dpa-acm.yaml
  retries: 100
  delay: 5
  register: result
  until: result is success


