apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: hello-world-placement
  namespace: default
spec:
  clusterSets:
  - global
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - managed-cluster
