- name: Extract all secrets from ACM cluster becoming passive
  kubernetes.core.k8s_info:
    host: "{{passive_hub_ocp_host}}"
    api_key: "{{passive_hub_ocp_api_key}}"
    validate_certs: "{{passive_hub_ocp_validate_certs}}"
    api_version: v1
    kind: Secret
  no_log: True
  register: passive_hub_secrets
 
- name: Count the number of auto-import secrets in ACM cluster becoming passive
  set_fact:
    passive_hub_auto_import_secret_count: "{{passive_hub_secrets.resources | selectattr('metadata.name', 'defined') | map(attribute='metadata.name') | select('match', '.*auto-import.*') | length }}"

- name: Fail if passive_hub_auto_import_secret_count == 0 before update BackupSchedule
  fail:
    msg: "You should see there are auto-import-account secrets in each managed cluster namespace  using the command 'oc get secrets -A | grep auto-import'"
  when: passive_hub_auto_import_secret_count == "0"

- name: "Define parameter 'useManagedServiceAccount: false' in BackupSchedule resource of ACM HUB becoming passive"
  kubernetes.core.k8s:
    host: "{{passive_hub_ocp_host}}"
    api_key: "{{passive_hub_ocp_api_key}}"
    validate_certs: "{{passive_hub_ocp_validate_certs}}"
    api_version: cluster.open-cluster-management.io/v1beta1
    kind: BackupSchedule
    namespace: "open-cluster-management-backup"
    name: "schedule-acm"
    state: present
    definition: |
      spec:
        useManagedServiceAccount: false

- name: Pause for 2 minutes waiting auto-import secrets are deleted
  ansible.builtin.pause:
    minutes: 2

- name: Extract all secrets from ACM cluster becoming passive
  kubernetes.core.k8s_info:
    host: "{{passive_hub_ocp_host}}"
    api_key: "{{passive_hub_ocp_api_key}}"
    validate_certs: "{{passive_hub_ocp_validate_certs}}"
    api_version: v1
    kind: Secret
  no_log: True
  register: passive_hub_secrets
 
- name: Count the number of auto-import secrets in ACM cluster becoming passive
  set_fact:
    passive_hub_auto_import_secret_count: "{{passive_hub_secrets.resources | selectattr('metadata.name', 'defined') | map(attribute='metadata.name') | select('match', '.*auto-import.*') | length }}"

- name: Fail if passive_hub_auto_import_secret_count == 0 after update BackupSchedule
  fail:
    msg: "This time you should see no auto-import-account secrets using the command  'oc get secrets -A | grep auto-import' "
  when: passive_hub_auto_import_secret_count != "0"
