apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: "{{ namespace_node_selector['open-cluster-management'] }}"
  name: open-cluster-management
spec:
  finalizers:
  - kubernetes