- hosts: localhost
  gather_facts: off
  tasks:
   - name: Configure restore from GCP S3 to primary RH ACM Hub
     include_role:
       name: acm_restore_configure
     vars:
       host: "{{primary_hub_ocp_host}}"
       api_key: "{{primary_hub_ocp_api_key}}"
       validate_certs: "{{primary_hub_ocp_validate_certs}}"
