- hosts: localhost
  gather_facts: off
  tasks:
   - name: Install primary RH ACM on ARO
     include_role:
       name: acm_install
     vars:
       host: "{{primary_hub_ocp_host}}"
       api_key: "{{primary_hub_ocp_api_key}}"
       validate_certs: "{{primary_hub_ocp_validate_certs}}"       
       certs: "{{primary_hub_ocp_validate_certs}}"
       mch_enable_cluster_backup: "true"
       mch_enable_managedserviceaccount_preview: "true"

   - name: Install secondary RH ACM on ROSA
     include_role:
       name: acm_install
     vars:
       host: "{{secondary_hub_ocp_host}}"
       api_key: "{{secondary_hub_ocp_api_key}}"
       validate_certs: "{{secondary_hub_ocp_validate_certs}}"
       mch_enable_cluster_backup: "true"
       mch_enable_managedserviceaccount_preview: "true"

   - name: Import a managed cluster on primary RH ACM Hub
     include_role:
       name: acm_import_managedcluster
     vars:
       hub_host: "{{primary_hub_ocp_host}}"
       hub_api_key: "{{primary_hub_ocp_api_key}}"
       hub_validate_certs: "{{primary_hub_ocp_validate_certs}}"
       managed_cluster_host: "{{managed_cluster_ocp_host}}"
       managed_cluster_api_key: "{{managed_cluster_ocp_api_key}}"
       managed_cluster_validate_certs: "{{managed_cluster_ocp_validate_certs}}"

   - name: Deploy a simple helloworld policy on on primary RH ACM Hub
     include_role:
       name: acm_deploy_simple_policy
     vars:
       host: "{{primary_hub_ocp_host}}"
       api_key: "{{primary_hub_ocp_api_key}}"
       validate_certs: "{{primary_hub_ocp_validate_certs}}"


   - name: Configure backup on S3 on primary RH ACM Hub
     include_role:
       name: acm_backup_configure
     vars:
       host: "{{primary_hub_ocp_host}}"
       api_key: "{{primary_hub_ocp_api_key}}"
       validate_certs: "{{primary_hub_ocp_validate_certs}}"
       aws_access_key: "{{aws_access_key}}"
       aws_secret_key: "{{aws_secret_key}}"

   - name: Configure restore from S3 to secondary RH ACM Hub
     include_role:
       name: acm_restore_configure
     vars:
       host: "{{secondary_hub_ocp_host}}"
       api_key: "{{secondary_hub_ocp_api_key}}"
       validate_certs: "{{secondary_hub_ocp_validate_certs}}"
       aws_access_key: "{{aws_access_key}}"
       aws_secret_key: "{{aws_secret_key}}"